export const actionTypes = Object.freeze({
ADD_PORTAIL_ARTICLE: "ADD_PORTAIL_ARTICLE",
ADD_UTC_ARTICLE: "ADD_UTC_ARTICLE",
ADD_NOTIFICATION: "ADD_NOTIFICATION",
REACT_TO_PORTAIL_ARTICLE: "REACT_TO_PORTAIL_ARTICLE",
UPDATE_PORTAIL_ARTICLE_REACTION_SYNC_STATE: "UPDATE_PORTAIL_ARTICLE_REACTION_SYNC_STATE",
COMMENT_PORTAIL_ARTICLE: "COMMENT_PORTAIL_ARTICLE",
UPDATE_PORTAIL_ARTICLE_COMMENT_SYNC_STATE: "UPDATE_PORTAIL_ARTICLE_COMMENT_SYNC_STATE",
UPDATE_PORTAIL_ARTICLE_COMMENT_DATA_AND_SYNC_STATE: "UPDATE_PORTAIL_ARTICLE_COMMENT_DATA_AND_SYNC_STATE",
COMMENT_UTC_ARTICLE: "COMMENT_UTC_ARTICLE",
UPDATE_UTC_ARTICLE_COMMENT_SYNC_STATE: "UPDATE_UTC_ARTICLE_COMMENT_SYNC_STATE",
UPDATE_UTC_ARTICLE_COMMENT_DATA_AND_SYNC_STATE: "UPDATE_UTC_ARTICLE_DATA_AND_SYNC_STATE"
});
export const syncStates = Object.freeze({
LOCAL: "LOCAL",
UPLOADED: "UPLOADED",
REFUSED: "REFUSED",
NETWORK_FAILED: "NETWORK_FAILED"
});
